/**
 * /ingresar — Entry point (user-type gate) E2E tests.
 *
 * Verifies that:
 * - The entry page renders both options (coach / alumno)
 * - Coach option links to /login
 * - Alumno section shows QR code and two store cards
 */
import { test, expect } from '@playwright/test';

test.describe('/ingresar entry gate', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/ingresar');
  });

  test('page loads with FORZZA brand', async ({ page }) => {
    await expect(page.locator('nav').getByRole('link', { name: 'FORZZA' })).toBeVisible();
  });

  test('headline asks who you are', async ({ page }) => {
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  });

  test('coach card is visible and links to /login', async ({ page }) => {
    // The coach card is an <a href="/login">
    const coachCard = page.getByRole('link', { name: /ingresar como coach/i });
    await expect(coachCard).toBeVisible();
    await expect(coachCard).toHaveAttribute('href', '/login');
  });

  test('student card is visible and scrolls to download section', async ({ page }) => {
    const studentCard = page.getByRole('link', { name: /ver cómo descargar/i });
    await expect(studentCard).toBeVisible();
    await expect(studentCard).toHaveAttribute('href', '#descargar-app');
  });

  test('download section heading is visible', async ({ page }) => {
    await expect(page.getByRole('heading', { name: /forzza para alumnos/i })).toBeVisible();
  });

  test('QR code image is present', async ({ page }) => {
    // The QR is rendered as an <img> with a data: src
    const qr = page.locator('img[src^="data:"]');
    await expect(qr).toBeVisible();
    // Confirm it's a PNG data URL (generated by qrcode library)
    const src = await qr.getAttribute('src');
    expect(src).toMatch(/^data:image\/png;base64,/);
  });

  test('App Store card is present with link', async ({ page }) => {
    const appStoreLink = page.getByRole('link', { name: /app store/i });
    await expect(appStoreLink).toBeVisible();
    // Link should be an external link (href starts with https)
    const href = await appStoreLink.getAttribute('href');
    expect(href).toMatch(/^https/);
  });

  test('Google Play card is present with link', async ({ page }) => {
    const playLink = page.getByRole('link', { name: /google play/i });
    await expect(playLink).toBeVisible();
    const href = await playLink.getAttribute('href');
    expect(href).toMatch(/^https/);
  });

  test('clicking coach card navigates to /login', async ({ page }) => {
    const coachCard = page.getByRole('link', { name: /ingresar como coach/i });
    await coachCard.click();
    await page.waitForURL(/\/login/, { timeout: 8_000 });
    await expect(page).toHaveURL(/\/login/);
  });
});
